# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_fun_fix <- function(nsim, nburn, napprox, nparam, d, grid_l, data, grid, mu_start, Lambda_start, theta, m0, B0, nu0, sigma, b1, B1, m1, M1, s1, S1, nupd, plim) {
    .Call('_BNPmix_main_fun_fix', PACKAGE = 'BNPmix', nsim, nburn, napprox, nparam, d, grid_l, data, grid, mu_start, Lambda_start, theta, m0, B0, nu0, sigma, b1, B1, m1, M1, s1, S1, nupd, plim)
}

main_fun <- function(nsim, nburn, napprox, nparam, d, grid_l, data, grid, mu_start, Lambda_start, theta, m0, B0, nu0, sigma, b1, B1, m1, M1, s1, S1, t1, t2, nupd, plim) {
    .Call('_BNPmix_main_fun', PACKAGE = 'BNPmix', nsim, nburn, napprox, nparam, d, grid_l, data, grid, mu_start, Lambda_start, theta, m0, B0, nu0, sigma, b1, B1, m1, M1, s1, S1, t1, t2, nupd, plim)
}

find_part <- function(clust_mat) {
    .Call('_BNPmix_find_part', PACKAGE = 'BNPmix', clust_mat)
}

pairwise_mat <- function(clust_mat) {
    .Call('_BNPmix_pairwise_mat', PACKAGE = 'BNPmix', clust_mat)
}

est_ISE_2D <- function(estimated, teoric, grid) {
    .Call('_BNPmix_est_ISE_2D', PACKAGE = 'BNPmix', estimated, teoric, grid)
}

